modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Focamacho/RingsOfAscension/issues"
license="MIT"
[[mods]]
modId="ringsofascension"
version="1.0.0"
displayName="Rings of Ascension"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension"
description='''
Rings of Ascension is a mod that uses the Curios API to add 20+ new rings to your minecraft. Each ring has its own special effect that is activated when the ring is equipped.
'''
[[dependencies.ringsofascension]]
    modId="curios"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ringsofascension]]
    modId="forge"
    mandatory=true
    versionRange="[1.19-41.0.100,)"
    ordering="NONE"
    side="BOTH"